language: node_js
node_js:
- stable
- '4.3.0'
group: edge
os:
  - linux
env:
  global:
  - NODE_ENV=dev
install:
  - npm install -g istanbul mocha
  - npm install
script: mocha
after_script: echo "Running coverage..." && istanbul cover _mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
